index:
    path:      /
    defaults:  { _controller: AppBundle:Invoice:index }

add:
    path:      /add
    defaults:  { _controller: AppBundle:Invoice:add }

edit:
    path:      /edit
    defaults:  { _controller: AppBundle:Invoice:edit }

delete:
    path:      /delete
    defaults:  { _controller: AppBundle:Invoice:delete }

